### ISSUE TITLE
FTP status was '550 Requested action not taken; file unavailable'

### ISSUE THREAD

**Issue by MonnieMcGee** [lgatto/rpx#21]
I ran the following code using rpx for Bioc 3.16 running R 4.2.2 on an Intel Mac running OS 12.6. Errors are shown within the code. Note that I had no trouble loading the example data set. Other data sets (just 3 so far) that I have tried give me the same error as in the subject line. 

> library(rpx)
> my_cache <- BiocFileCache::BiocFileCache(tempfile())
using temporary cache /var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpfvV2EA/BiocFileCache
> my_cache
class: BiocFileCache
bfccache: /var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpfvV2EA/BiocFileCache
bfccount: 0
For more information see: bfcinfo() or bfcquery()
> px <- PXDataset2("PXD031685", cache = my_cache)
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") : 
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
> px <- PXDataset2("PXD000001", cache = my_cache)
Querying ProteomeXchange for PXD000001.
> my_cache
class: BiocFileCache
bfccache: /var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpfvV2EA/BiocFileCache
bfccount: 1
For more information see: bfcinfo() or bfcquery()

Clearly R can find my_cache because the example data set can be download (bfccount = 1).

Thanks for your attention to this! I'm teaching a bioinformatics course and I would really love for the students to be able to use rpx when we analyze flow data!

Monnie

**Comment by lgatto** [comment]
Thank you for the report. The problem comes for a missing README.txt file in that [PX project](http://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/). I believe that every PX project/directory should have one. 

@ypriverol - could you confirm/comment?

**Comment by MonnieMcGee** [comment]
If every PX project/directory should have a README file, then why doesn't this one? 

And it isn't just this one. I tried two or three others (I don't have the accession numbers written down).

How can I make sure to use PX projects with README files?

**Comment by lgatto** [comment]
@ypriverol should be able to confirm this.

**Comment by ypriverol** [comment]
Hi @lgatto sorry for the late reply. @MonnieMcGee is right. Not all the PX contains a README file, a README was created in the past by PRIDE pipelines, was not use by anyone and at some time we stop generating them. Do you need them for something special?

**Comment by lgatto** [comment]
That is exactly the recurring problem:   

> a README was created in the past by PRIDE pipelines, was not use by anyone and at some time we stop generating them  

It is impossible to make any assumptions because things change and break out of the blue. And this has happened several times in the past.

**Comment by lgatto** [comment]
@MonnieMcGee - I'll have to fix this. I don't think it is difficult to do, but I have very limited time. Will keep you posted here. Thank you for highlighting this issue!

**Comment by MonnieMcGee** [comment]
I wanted to use files from PX for a class that I am teaching in bioinformatics. So, yes, it’s something special. That said, I am not particular about the study data I use.

Sent from my iPhone

On Mar 7, 2023, at 5:03 AM, Yasset Perez-Riverol ***@***.***> wrote:

﻿

[EXTERNAL SENDER]

Hi @lgatto<https://github.com/lgatto> sorry for the late reply. @MonnieMcGee<https://github.com/MonnieMcGee> is right. Not all the PX contains a README file, a README was created in the past by PRIDE pipelines, was not use by anyone and at some time we stop generating them. Do you need them for something special?

**Comment by lgatto** [comment]
@ypriverol - the random changes to the PRIDE infrastructure are a pain in my backside. The number of issues in this repo show it. The day somebody at PRIDE understands backward compatibility will be a great relief. But I don't hold my breath...

**Comment by lgatto** [comment]
@MonnieMcGee - this should be fixed now:

```
> library(rpx)
> packageVersion("rpx")
[1] ‘2.6.1’
> PXDataset("PXD031685")
Querying ProteomeXchange for PXD031685.
Project PXD031685 with 39 files
 Resource ID BFC1235 in cache in /home/lgatto/.cache/R/rpx.
 [1] 'LUM2_1023541.mzML' ... [39] 'LUM2_803367.raw'
 Use 'pxfiles(.)' to see all files.
```

You can install the latest version right away with. 

```
BiocManager::install("lgatto/rpx")
```

I'll push the change to Bioconductor later today.

**Comment by lgatto** [comment]
I'm closing the issue, but feel free to re-open it if you still have any issues.

**Comment by lgatto** [comment]
FYI - version on Github is 2.7.1. This will also be the devel version. Release version will be 2.6.1.

**Comment by MonnieMcGee** [comment]
Oops. Mistyped your name. Sorry, Laurent. 

Monnie McGee, PhD
Associate Professor
Statistical Science
Southern Methodist University
Office: 214-768-2462
Fax: 214-768-4035
________________________________________
From: McGee, Monnie
Sent: Wednesday, March 8, 2023 10:39 AM
To: lgatto/rpx; lgatto/rpx
Cc: Mention
Subject: RE: [lgatto/rpx] FTP status was '550 Requested action not taken; file unavailable' (Issue #21)

Hi, Laurant,

It's still not working. See code below. I installed "lgatto/rpx" as directed.

My university will be on spring break next week. I can come back and try this again on March 17 or 18.

Monnie

> library(remotes)
> BiocManager::install("lgatto/rpx")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.2 (2022-10-31)
Installing github package(s) 'lgatto/rpx'
Downloading GitHub repo ***@***.***
Running `R CMD build`...
* checking for file ‘/private/var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T/RtmpGhU23u/remotes1f891669d4d8/lgatto-rpx-47b861c/DESCRIPTION’ ... OK
* preparing ‘rpx’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘rpx_2.7.1.tar.gz’
* installing *source* package ‘rpx’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rpx)
> library(rpx)
> my_cache <- BiocFileCache::BiocFileCache(tempfile())
/var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpGhU23u/file1f8948ade7e0
  does not exist, create directory? (yes/no): yes
> my_cache
class: BiocFileCache
bfccache: /var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpGhU23u/file1f8948ade7e0
bfccount: 0
For more information see: bfcinfo() or bfcquery()

> px <- PXDataset2("PXD031685", cache = my_cache)
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") :
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
> PXDataset("PXD031685")
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") :
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
> library(lgatto/rpx)
Error in library(lgatto/rpx) : 'package' must be of length 1
> library("lgatto/rpx")
Error in library("lgatto/rpx") : there is no package called ‘lgatto/rpx’
> PXDataset("PXD031685", cache=my_cache)
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") :
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
>

Monnie McGee, PhD
Associate Professor
Statistical Science
Southern Methodist University
Office: 214-768-2462
Fax: 214-768-4035
________________________________________

**Comment by MonnieMcGee** [comment]
Hi, Laurant,

It's still not working. See code below. I installed "lgatto/rpx" as directed. 

My university will be on spring break next week. I can come back and try this again on March 17 or 18.

Monnie

> library(remotes)
> BiocManager::install("lgatto/rpx")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.2 (2022-10-31)
Installing github package(s) 'lgatto/rpx'
Downloading GitHub repo ***@***.***
Running `R CMD build`...
* checking for file ‘/private/var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T/RtmpGhU23u/remotes1f891669d4d8/lgatto-rpx-47b861c/DESCRIPTION’ ... OK
* preparing ‘rpx’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘rpx_2.7.1.tar.gz’
* installing *source* package ‘rpx’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rpx)
> library(rpx)
> my_cache <- BiocFileCache::BiocFileCache(tempfile())
/var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpGhU23u/file1f8948ade7e0
  does not exist, create directory? (yes/no): yes
> my_cache
class: BiocFileCache
bfccache: /var/folders/z9/tycx8gl55nz3g4ll83j03_5h0000gp/T//RtmpGhU23u/file1f8948ade7e0
bfccount: 0
For more information see: bfcinfo() or bfcquery()

> px <- PXDataset2("PXD031685", cache = my_cache)
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") : 
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
> PXDataset("PXD031685")
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") : 
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
> library(lgatto/rpx)
Error in library(lgatto/rpx) : 'package' must be of length 1
> library("lgatto/rpx")
Error in library("lgatto/rpx") : there is no package called ‘lgatto/rpx’
> PXDataset("PXD031685", cache=my_cache)
Querying ProteomeXchange for PXD031685.
Error in file(file, "rt") : 
  cannot open the connection to 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2022/11/PXD031685/README.txt': FTP status was '550 Requested action not taken; file unavailable'
> 

Monnie McGee, PhD
Associate Professor
Statistical Science
Southern Methodist University
Office: 214-768-2462
Fax: 214-768-4035
________________________________________

**Comment by lgatto** [comment]
Have you restarted your R session? Here's what I have in a new one:

```r
> BiocManager::install("lgatto/rpx")
*** output flushed ***
> packageVersion("rpx")
[1] ‘2.7.1’
> library("rpx")
> my_cache <- BiocFileCache::BiocFileCache(tempfile())
/tmp/RtmpdvUHQ6/file93a92903ee7
  does not exist, create directory? (yes/no): yes
> px <- PXDataset2("PXD031685", cache = my_cache)
Querying ProteomeXchange for PXD031685.
> px
Project PXD031685 with 39 files
 Resource ID BFC1 in cache in /tmp/RtmpdvUHQ6/file93a92903ee7.
 [1] 'LUM2_1023541.mzML' ... [39] 'LUM2_803367.raw'
 Use 'pxfiles(.)' to see all files.
```

If you still have an error with the code above, in a new session, please also provide you session information, as shown below:

```r 
> sessionInfo()
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rpx_2.7.1

loaded via a namespace (and not attached):
 [1] compiler_4.2.2      pillar_1.8.1        BiocManager_1.30.20
 [4] dbplyr_2.3.1        bitops_1.0-7        prettyunits_1.1.1  
 [7] remotes_2.4.2       tools_4.2.2         pkgbuild_1.4.0     
[10] bit_4.0.5           jsonlite_1.8.4      BiocFileCache_2.6.1
[13] RSQLite_2.3.0       memoise_2.0.1       lifecycle_1.0.3    
[16] tibble_3.1.8        pkgconfig_2.0.3     rlang_1.0.6        
[19] DBI_1.1.3           cli_3.6.0           filelock_1.0.2     
[22] curl_5.0.0          fastmap_1.1.1       xml2_1.3.3         
[25] withr_2.5.0         dplyr_1.1.0         httr_1.4.5         
[28] rappdirs_0.3.3      desc_1.4.2          generics_0.1.3     
[31] vctrs_0.5.2         rprojroot_2.0.3     bit64_4.0.5        
[34] tidyselect_1.2.0    glue_1.6.2          R6_2.5.1           
[37] processx_3.8.0      fansi_1.0.4         purrr_1.0.1        
[40] callr_3.7.3         blob_1.2.3          magrittr_2.0.3     
[43] ps_1.7.2            utf8_1.2.3          RCurl_1.98-1.10    
[46] cachem_1.0.7        crayon_1.5.2       
```
